### ISSUE TITLE
Does not open files in default editor despite configuration

### ISSUE THREAD

**Issue by nshdesai** [Canop/broot#138]
**Description**
Broot will open files in gedit on Ubuntu 18.04 despite having set the default to be vim. Probably an install issue (but I'm not sure). It was installed using cargo and didn't create the `br` command (even after running the program to create the `br` command. Finally ended up using `alias broot=br`

**Configuration:**
 - OS: Ubuntu 18.04.3
 - Default editor set to be vim in `~/.bash_profile`
 - Broot was installed using cargo

**Comment by Canop** [comment]
Where did you set the default ? Is it different from what happens when you double-click the icon of your file ?

In any case you can directly set the editor in conf.toml to be used with for example `:e`

```
[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "/usr/bin/vim {file}"
```

**Comment by nshdesai** [comment]
Hmm. Seems to open with gedit even when double click on the icon. Maybe my default editor config is broken (I set it in my `~/.bash_profile`). `:e` worked with vim, earlier too. It was just in cases where I hit enter after finding a file that it opened it using gedit.

**Comment by Canop** [comment]
configuring xdg-open and similar tools is a PITA. For everybody and for every OS I tried...

**Comment by rkumar** [comment]
I am on Mac OS. Pressing Enter attempts to open a text file using Xcode. I would prefer to open with `vim` in the terminal, since I do not even have xcode.  I was asked on HN to configure key in conf.toml.
However, this is what I get if I replace "F2" with "enter".

`Bad configuration: not a valid key: enter`

I am not sure this can be configured at the OS level, as I would have to select a GUI tool to open files in from the Finder.

**Comment by Pofilo** [comment]
On a server without server X, user is forced to configure xdg-open (which is a bit difficult ..), so if I press Enter, nothing happens, and alt-enter closes broot without opening anything.

**Comment by kdwarn** [comment]
> configuring xdg-open and similar tools is a PITA. For everybody and for every OS I tried...

I just had an issue with this and wanted to share my solution (on POP_OS! 21.04). I wanted files to be opened by vim, in alacritty. 

First, I created a file named vim.desktop in ~/.local/share/applications:
```
[Desktop Entry]
Name=Vim Text Editor
Comment=Edit text files
Exec=alacritty -e vim
Terminal=false
Type=Application
Icon=terminal
Categories=Utility;TextEditor;
StartupNotify=true
MimeType=text/plain;
```

Then, I ran `xdg-mime default vim.desktop text/plain` to associate plaintext files to this desktop entry.

If you don't use alacritty and want to use the default terminal, this would be your vim.desktop file:
```
[Desktop Entry]
Name=Vim Text Editor
Comment=Edit text files
Exec=vim
Terminal=true
Type=Application
Icon=terminal
Categories=Utility;TextEditor;
StartupNotify=true
MimeType=text/plain;
```
Bonus is that double-clicking on plain texts files via Nautilus now opens them in Vim instead of gedit, too.

These are the links that helped me put this together:
https://askubuntu.com/a/1238117/91376
https://unix.stackexchange.com/a/177979/416095

**Comment by Canop** [comment]
Thanks for putting that here. I'll also probably allow direct mapping from extension to opener in broot with a filter on verbs.

**Comment by TheKevJames** [comment]
It's unfortunate that if we take the approach outlined in the config (https://dystroy.org/broot/documentation/tricks/#open-files-without-a-windowing-system), we can't override the alt-enter behaviour as well (or, at least, I attempted to and could not seem to get it to work -- if it does work, then it's unfortunate that we have to override the configs for all multiple builtin methods of opening files.

I wonder if it might be reasonable to expose this as a more global config option? eg. something like:
```
default_open_cmd: "xdg-open"  # or swap to "$EDITOR", etc
```

**Comment by izaac** [comment]
In case someone is trying this in Fedora this is the package you'd need: `qt5-qttools`
