### ISSUE TITLE
Allow use of forward-slash >/< to select and navigate. Also don't panic

### ISSUE THREAD

**Issue by harikb** [Canop/broot#180]
I had a directory structure like `dev/code/src`. After typing dev, I *incorrectly* assumed I can type the rest of the path. May be a habit. But `br` took it as a regex flag. Then `code` became an unrecognized flag. Morover, it panicked and died.

**To Reproduce**
Just type the string `dev/code/src` while inside `broot`

**Expected behavior**
Ideally work as a I expected. But it should be OK to error/beep without exiting the application.

**Screenshots**
```% br
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:1165:5

% broot --version
broot 0.12.0
```

**Configuration (please complete the following information):**
 - OS: macOS Catalina
 - Version : Catalina
- Relevant configuration items

**Additional context**
I just installed `broot` via cargo (just today, so latest release I assume). Shell is the Catalina default of `zsh`

**Comment by harikb** [comment]
I can confirm the panic happens for any string `foo/bar/` (right when the last forward-slash is typed)

**Comment by Canop** [comment]
There are two separate questions here:

1) the crash: it's the same problem than https://github.com/Canop/broot/issues/175. The fix is pushed but not in a released version. I guess I should release a new version

2) being able to do searches on paths (and not just file names). This calls for a different syntax and I handle the question here: https://github.com/Canop/broot/issues/164
