### ISSUE TITLE
Mac: '--whale-spotting' emits 's' artefact next to size (0.18.4)

### ISSUE THREAD

**Issue by bluz71** [Canop/broot#244]
Hello,

On Mac I am now seeing a visual quirk when `--whale-spotting`, there are extra `s`s, in orange, being emitted as displayed in this screenshot:

<img width="407" alt="broot_whale_spotting" src="https://user-images.githubusercontent.com/11382509/86525449-89a22e80-beca-11ea-8c27-e4431f5f387c.png">

Version 0.18.4 via Homebrew.

Same 0.18.4 version on Linux (also via Homebrew) is fine, **no extra** `s`s. So I would assume a Mac only issue.

A previous version, I can't say which, did not do this on Mac. With Homebrew I can't recall whether I was running 0.18.x or 0.17.x; but this quirk is somewhat new.

Best regards.

**Comment by Canop** [comment]
@bluz71 The `s` means the file is sparse. This shouldn't appear on directories, I'll look at that.

**Comment by bluz71** [comment]
Thanks.

I can confirm that pretty much every directory on my system is being marked with `s`.

**Comment by Canop** [comment]
That's because you have a few sparse files and when I add the sizes of the files to compute directory sizes I consider that the directory is kind of sparse (done here: https://github.com/Canop/broot/blob/master/src/file_sum/mod.rs#L124).

It's better to display the `s` only on files. They're a distraction on directories. I'll do the change.

**Comment by bluz71** [comment]
Yes, I agree.

I look forward to the upcoming change.

Many thanks.

**Comment by Canop** [comment]
I'll try to do a release today but it's not certain

**Comment by Canop** [comment]
I published the 0.18.5
