### ISSUE TITLE
Cursor starts blinking after a broot session

### ISSUE THREAD

**Issue by isene** [Canop/broot#288]
**Is everything clear?**
We prefer you come to the chat and speak about the problem first.
Broot chat room: https://miaou.dystroy.org/3490?broot 

No-one in chat.

**Describe the bug**
I run zsh with a non-blinking cursor. When entering br and back to my zsh, the cursor now blinks. How can I stop broot from making the cursor blink?

**Comment by Canop** [comment]
When using my terminal's setting to disable cursor blinking, broot doesn't break it.

So I'd need to know how exactly you configure your non-blinking cursor so that I can reproduce the problem.

**Comment by isene** [comment]
I have no idea, actually - I've never had a blinking cursor and I don't see anything in my .zshrc or my .Xresources that specifically sets the cursor to not blink.

**Comment by Canop** [comment]
The cursor starts blinking in Broot because of https://github.com/Canop/broot/blob/master/src/cli.rs#L251

The right solution would be to determine if the cursor is set to blink before, so as to restore it only if it was blinking initially.

The problem is to determine that state... I'll do some research as soon as possible but any help on that point would be welcome.

**Comment by Canop** [comment]
If nobody finds a clean way to determine whether the cursor is blinking, I'll resort to a conf setting. But it's ugly ^^
