### ISSUE TITLE
make it possible to not leave broot when editing a file

### ISSUE THREAD

**Issue by Canop** [Canop/broot#38]
The hardest case will be the one where the terminal must be given to the editor (vi, emacs, etc.).

In the meantime #37 would offer a workaround

**Comment by Canop** [comment]
For non terminal editor, it's solved since version 0.9.

**Comment by Canop** [comment]
It's also possible with terminal editors (in a new terminal).

**Comment by nicklan** [comment]
It seems however that broot doesn't keep functioning until the editor is exited.  Is that expected/desired? Ideally it would pop open your editor, but keep working (i.e. run it in the background).  As it is, broot seems to "freeze" until I close my emacs, and then it processes anything I've typed in-between.

**Comment by Canop** [comment]
@nicklan 
Right now broot can either 

* open your terminal application in another terminal
* quit and launch your terminal application in the same terminal

I currently don't see how to "freeze" and have another application temporarily run, and then on quit have broot take over. Maybe with a subshell ?

I should probably investigate this so I reopen the issue.

**Comment by nicklan** [comment]
sorry, i think i wasn't clear enough in my previous comment.

i don't want it to freeze, it's just that it does.  maybe that's just a bug.  I want to be able to fire off my editor, and then switch back to my terminal and keep using broot, but when I leave the editor open, broot is frozen and doesn't process keystrokes until i close the editor.

**Comment by oj-lappi** [comment]
Hey, 

I solved this issue for my specific case, I run linux, xdg, and i3.

I had the same issue, files open, but this blocks broot.
E.g. if I open a pdf, my pdf viewer is launched (or the .desktop associated with application/pdf by xdg-mime), but broot does not process input anymore.
And if I open a text file -- associated with nvim.desktop -- broot freezes and no new window is launched.

It seems to me that something like this is happening: 
broot is not disowning the processes it launches to open files. 

I wrote a shell script that launches xdg-open and then disowns the process. If I configure broot to use this shell script instead of xdg-open, it works for gui programs, but obviously not for programs that need terminals.

The script: ```xdg-open-detached```:

```
#!/bin/sh
if [[ -z $1 ]]
then
        echo "No file to open"
exit 1
fi
xdg-open $1 &>/dev/null & disown
```

conf.toml:

```
...
[[verbs]]
invocation="open_stay"
shortcut="os"
key="enter"
leave_broot=false
execution="xdg-open-detached {file}"
...
```

Now I understand that launching a terminal is a lot more complicated, and you can't make many assumptions about peoples desktop environments, terminal emulators etc., so I don't know how this could actually be solved from within broot. I think I will simply change my .desktop files to gui those of gui programs, like nvim-qt.desktop instead of nvim.desktop, since I rarely every use xdg-open from a non-desktop environment, and stick to my shell script.

Hopefully this helps someone else as well :)
