### ISSUE TITLE
highlight vue files under ctrl ->

### ISSUE THREAD

**Issue by laoshaw** [Canop/broot#464]
the newest version can not highlight vue files, bat can highlight it well.

**Comment by Canop** [comment]
I'm sorry, I don't understand. Can you try be more precise, maybe with a screenshot ?

**Comment by laoshaw** [comment]
yes. below the highlighted one is from bat, the plain one is from `br -s` with `ctrl + ->`

![yy](https://user-images.githubusercontent.com/18351761/141987556-dec18aee-e84e-475d-bee4-876c802a16a7.png)
![xx](https://user-images.githubusercontent.com/18351761/141987565-c285e70b-035e-4052-88f4-cf387178fd7f.png)

**Comment by Canop** [comment]
Oh, Ok, it's about syntax highlighting in the preview. I'll have a look.
Do you have a link to a vue file, to help me test ?

**Comment by Canop** [comment]
Syntect doesn't include any definition for vue files.
The bat project maintains a huge list of submodules for the definitions.
I should probably use their own list (their assets directory) as a submodule in broot, to include all the syntaxes in broot's binary.

There would be a downside: bat's binary is big because of those definitions.

**Comment by Canop** [comment]
I'll probably do a release tonight or tomorrow
![image](https://user-images.githubusercontent.com/617006/142238748-38e7f027-20b2-4640-bd32-377021e849f3.png)
