### ISSUE TITLE
Feature request: Collapse/uncollapse directories

### ISSUE THREAD

**Issue by dgrisham** [Canop/broot#54]
Curious whether there's interest in a feature to toggle whether directories are collapsed or not. For example, it'd be nice to be able to collapse all directories in the current root -- so you'd only see files and directories directly in the current root. It would also be nice to be able to toggle whether a directory is collapsed so you could quickly check the first few files in a directory.

My use case for this would be general navigation of code projects, especially in the context of introducing a new codebase to someone. It's really nice to be able to see a project's structure and focus on specific directories in these cases, and this ability to control collapsing of directories would help that a lot.

**Comment by Canop** [comment]
@dgrisham I'll think about it. Right now I'll be more focused in windows compatibility but I'll experiment in that direction afterwards.

FYI the main motivation of broot was also navigation into code projects.

**Comment by Canop** [comment]
This isn't the right approach. It's more efficient to go (with the enter key) into the directory, then to go back (with the esc key).
If necessary you can toggle root trimming (with `:t`).

**Comment by Abdillah** [comment]
I would say in term of navigation and jump, current broot is superior. But I hope, broot somehow support collapsible directory navigation.

The reason is somehow close to the main goal described above.

> the main motivation of broot was also navigation into code projects.

When working on large or highly structured code project, directory structure is helpful to recall the structure of codes. For example when doing code refactoring or simply analyzing the current structure (learning code). File structure is what connect one code from another, if displayed in structured view lift the burden of the brain in remembering "where's the code in which file in which folder".

**Comment by ww7** [comment]
I'm also wondering about collapse/uncollapse directories 
For now my workaround is invocation of nnn/ranger by key

```
    {
        invocation: nnn
        key: ctrl-n
        leave_broot: false
        execution: "nnn {file}"
    }
    {
        invocation: xplr
        key: ctrl-x
        leave_broot: false
        execution: "xplr {file}"
    }
    {
        invocation: ranger
        key: ctrl-r
        leave_broot: false
        execution: "ranger --selectfile={file}"
    }
```

Only thing, I don't know if possible to return new path to Broot, can we? @Canop
