### ISSUE TITLE
Regex escape sequences require one extra backslash

### ISSUE THREAD

**Issue by FedericoStra** [Canop/broot#592]
I don't know whether this is the intended behavior, but I find it strange and confusing: regex search patterns require a *double backslash* to enter metacharacters and character classes.

For instance:
- `r/\\(` instead of `r/\(`,
- `r/\\d` instead of `r/\d`,
- `r/\\W` instead of `r/\W`,
- etc..

It's as if a single backslash on its own gets discarded: for instance `r/\\.\t\x\t\$` will find files with a `.txt` extension.

**Comment by Canop** [comment]
I'll review escaping and I'll probably change the rules.

**Comment by Canop** [comment]
There are escaping rules because the '&', '|', ' ', ':', ')' can all end a pattern.

Example:

![image](https://user-images.githubusercontent.com/617006/192158827-317e1618-1ba6-474f-b7a1-0f5e9fc257b9.png)

So escaping has a reason.

Now, I think escaping could have more complex rules so that less escaping is needed. I'll test some new rules.

**Comment by FedericoStra** [comment]
While parsing the request string, I would say that when `/` is encountered and we enter "regex mode" then `&`, `|`, `)`, etc. should lose their special meaning until we encounter the `/` that closes the regex.

**Comment by Canop** [comment]
That's the idea I'm testing.

- when after '/': only ' ', ':',  '/' and '\' need escaping
- otherwise, '&,' '|', '(', ')' need escaping too

The reason for the '(' is symmetry: it's easier to read.

**Comment by Canop** [comment]
@FedericoStra The new-escaping-rules branch tests, well, the new escaping rules.

In my first fast tests, it looks intuitive enough and there's much less to escape.

A regex followed by a verb invocation:
![image](https://user-images.githubusercontent.com/617006/192595889-3f03becf-75a7-4f04-9aa4-30e59760c8d8.png)

A composite pattern (3 basic patterns):
![image](https://user-images.githubusercontent.com/617006/192596016-a99b2c5b-0fda-41ac-b819-20bdabd6143e.png)

A composite pattern involving a content search with a \ and a space and a regex pattern:
![image](https://user-images.githubusercontent.com/617006/192596131-90df4b84-26ca-4bad-a74a-d1f4bf75999e.png)

**Comment by Canop** [comment]
I'll do other tests but in the meantime I'd welcome yours.

**Comment by FedericoStra** [comment]
Sounds great! In the meantime, I explored the structure of the `broot` codebase in general. With a bit of searching, I managed to identify that https://github.com/Canop/broot/blob/master/src/command/parts.rs#L34-L99 is the function responsible for parsing the search string, but didn't have time to modify it to suit what I had in mind. I'll have a look at your modification as soon as I find the time (that'll be ~ 1 week unfortunately).

**Comment by Canop** [comment]
Yes, that's where I did all the changes: https://github.com/Canop/broot/commit/3708784ec354d1bae52c7f7e0390efad7ae5788e

(except a few other changes in the bet library to ease unit testing)

**Comment by Canop** [comment]
I realized that I had forgotten to test whether we're between slash, which broke a lot of tests. And I had also forgotten to put the `'!'` in the list of escapable characters, which made it non searchable.

I think the last commit solves the issues you saw (except a few leniancies which are features in my eyes, because `&` doesn't need to be escaped IMO in first position as it can't be an operator).

Of course my last commit doesn't answer all your points, and I'll only make a fast answer right now because I lake time at the moment.

I'm not against a proper formal grammar but I'm afraid this would eat a lot of time and not really be needed once the language is settled (and until new needs make it change again). I'll still have a look at you prototype as soon as I find some time and I'll think more about that.

Regarding nom, I'm not super enthusiastic because of how slow I found it to be in practice due to the lot of lookups. The approach has the advantage of being straightforward and avoiding errors but I'd rather avoid it in simple cases.

But I've just made a fast fix of the thing I had forgotten. More tests are needed before deciding whether my hacky fast approach is enough or not.
