### ISSUE TITLE
`$EDITOR` with a space in it's path causes an error

### ISSUE THREAD

**Issue by brian6932** [Canop/broot#662]
![image](https://user-images.githubusercontent.com/18603393/216529572-3b94d9ea-8f06-44dd-b120-de4d6ed88c44.png)

**Comment by Canop** [comment]
Broot can't really do anything here because it can't know whether the $EDITOR string is just one path or a path to a program followed by arguments.

Besides, you'd have the same problem with other scripts using $EDITOR.

What I suggest is either to set $EDITOR to a path without spaces (can be a link) or you directly write the path in the `config/broot/verbs.hjson` file, using the array syntax:

```Hjson
    {
        invocation: edit
        shortcut: e
        execution: ["/some path/with spaces/nvim", "+{line}", "{file}"]
        leave_broot: false
    }
```
(this would replace the definition of edit which is already in the config file)

**Comment by brian6932** [comment]
yea that works, thank you
