### ISSUE TITLE
Show all folders in --whale-spotting mode

### ISSUE THREAD

**Issue by Schweber** [Canop/broot#669]
I've defined several folders as "no-enter", e.g. `~/.local`.

However, when launching broot in `--whale-spotting` mode, i would like to see all folders. I'm not aware of a way to do this and didn't find a flag for it.

Is this already possible and, if not, could this be added as an additional flag? Something like `--ignore-special-paths` (just an example, i hope you understand what i mean).

**Comment by Canop** [comment]
I understand what you mean.

It will be hard to satisfy all needs.

Some folders are really not explorable, because they're *way* too slow.
Some other ones are just not entered because they're simply full of trash.

The real solution might be to add more nuances in the special paths directive, to have a _"no enter but of course you enter if when it's for computing sizes"_ and a _"no enter, especially not for computing sizes"_.

**Comment by Schweber** [comment]
> The real solution might be to add more nuances in the special paths directive, to have a _"no enter but of course you enter when it's for computing sizes"_ and a _"no enter, especially not for computing sizes"_.

That would be even better. Thank you for considering it!
