### ISSUE TITLE
[Windows] broot -c 'filter;:pt' does not filter

### ISSUE THREAD

**Issue by AeliusSaionji** [Canop/broot#699]
Under Windows, `broot -c filter;:pt` (including :cd and I'm sure anything that exits broot) always skips the filter part. The command runs as if no filter were given.

Let me know if you need me to help debug!

**Comment by Canop** [comment]
Can you run the same command with debug log enabled and publish the log so that we see what arguments are really received by broot ?
See https://dystroy.org/broot/community/#log

(if it's not clear, drop by t[he chat](https://miaou.dystroy.org/3490) during west-european hours)

**Comment by AeliusSaionji** [comment]
No problem-
[broot.log](https://github.com/Canop/broot/files/11279569/broot.log)

I ran this in nushell, but the behavior is the same in pwsh/powershell.

**Comment by Canop** [comment]
I don't see the problem. Same command (with quotes: `broot -c "ep/file2;:pt"`) runs fine on my side.

Can you try with broot version 1.21.2 (either released or from the repo) ? It has some additional log and I might find the difference with when I run this command locally on linux.

**Comment by AeliusSaionji** [comment]
Sorry for the delay. Here's 1.21.2's log

[broot.log](https://github.com/Canop/broot/files/11360503/broot.log)

**Comment by Canop** [comment]
It confirms that the command is correctly interpreted... the filtering is just skipped and I have no idea why...
I'll try to see if I can find a Windows computer to try reproduce.

**Comment by AeliusSaionji** [comment]
Along a similar line `br -c :pt -w` is simply skipping calculating directories

**Comment by Canop** [comment]
Trying on Windows I could determine that the problem is that powershell sends to broot a `Resize` event *after* it was launched, which interrupts its task. Asking broot to wait for 10ms before working on its task queue solves the problem.

I guess most programs Microsoft tested didn't start to work fast enough for that delay to be a problem...

**Comment by Canop** [comment]
Trying on Windows I could determine that the problem is that powershell sends to broot a `Resize` event *after* it was launched, which interrupts its task.

I guess most programs Microsoft tested didn't start fast enough for that to be a problem...

Asking broot to wait for 10ms before cleaning its event queue and then working on its task queue solves the problem.

**Comment by Canop** [comment]
@AeliusSaionji PR #701 seems to solve the problem. Can you check ?

**Comment by AeliusSaionji** [comment]
All fixed over here, thanks!

**Comment by Canop** [comment]
It's in release 1.21.3
