### ISSUE TITLE
typing in sizes mode seems to search only in current dir

### ISSUE THREAD

**Issue by helix84** [Canop/broot#80]
**Describe the bug**
In sizes mode (in contrast to normal mode), typing finds files/directories only in the current directory, not in subdirectories.

**To Reproduce**
mkdir -p foo/bar/baz
cd foo
br --sizes
baz

**Expected behavior**
I expected to find baz even though it is located in a subdirectory, same thing as br would do outside of the sizes mode.

**Screenshots**
![br](https://user-images.githubusercontent.com/201026/72046934-b37eed80-32b9-11ea-88b0-4f3dec5faa66.png)

**Configuration (please complete the following information):**
 - OS: Debian 9 stretch
 - Version: broot 0.11.2

**Comment by Canop** [comment]
This is by design. This may change but right now toggling the size display changes the mode to only show a level of the hierarchy and sorts files and directories.

The rationale is that this is more helpful when you want to see what takes space on your disk.

I agree this isn't ideal and there should be both
- a way to just display file size
- a fat file search mode
