### ISSUE TITLE
Please answer: do you use the br shell function for anything else than cd ?

### ISSUE THREAD

**Issue by Canop** [Canop/broot#824]
I suspect nobody needs the shell function to output the whole command: you don't need it for anything else than cd on quit.

Specializing this function would solve various problems but I need first to be sure I break no workflow.

**Comment by Martin1887** [comment]
Nothing more in my side.

**Comment by seomwan** [comment]
Not yet 😛

**Comment by Canop** [comment]
Ok. I feel free to change br to focus on cd.

**Comment by seomwan** [comment]
Out of curiosity, what difference would this make? 

Since I posted it, I use br to navigate and switch to shell (ctrl+t) a lot. I assume it does a similar thing to cd so nothing much would change, or..?

I also made a few custom verbs that don't exit br. 

Tbh, I have no idea what difference this would make, or if I'd be affected at all.. 
Maybe an example would help here?
