### ISSUE TITLE
nushell: `cd` not working

### ISSUE THREAD

**Issue by Schweber** [Canop/broot#827]
I am using broot 1.32.0 with nushell 0.89.0 and applied the argument expansion to the `br` shell function from https://github.com/Canop/broot/issues/821

However, `:open_leave` doesn't work for me in nushell. I've set `{ key: "enter", execution: ":open_leave" }` but if i press enter on a file/directory in broot, i'm back in the terminal without the folder having changed. Running `pwd` confirms this, so it's not a problem of the prompt not being updated.

Using `{ invocation: "cd", key: "enter", execution: "$SHELL", set_working_dir: true }` "works" but this launches an additional instance of `nu` with the given folder so it's not a good workaround.

What could be the reason for this?

**Comment by Canop** [comment]
Just to be sure: you launch `br,` not `broot` ?

**Comment by Canop** [comment]
`:open_leave` isn't supposed (or able) to change the current directory of the opening shell.

Try with this:

    {
        key: enter
        internal: open_leave
        apply_to: file
    }
    {
        key: enter
        external: "cd {directory}"
        from_shell: true
        apply_to: directory
    }

**Comment by Canop** [comment]
> Is there a way to get a verbose output of broot to see why it fails? I found no such cli option...

Yes, there's a log: https://dystroy.org/broot/community/#log

**Comment by Canop** [comment]
You don't have other verbs than the one I proposed mapped to the enter key ?

I'll have a deeper look and try on nushell but it won't be before a few days.

**Comment by FrancescElies** [comment]
@Schweber I think this is spected because of nushell [scoping rules](https://www.nushell.sh/book/environment.html#defining-environment-from-custom-commands), the environment changes inside your def function stay there and do not have side effects outside the funciton, try with `def --env a [] { br -gis }`.

`def --env` is also what we used to define the br wrapper for nushell, see [here](https://github.com/Canop/broot/blob/main/src/shell_install/nushell.rs#L36)

Does this help?
