### ISSUE TITLE
root path/top bar not visible in windows

### ISSUE THREAD

**Issue by flxn7** [Canop/broot#840]
Hello canop,

I'm on windows without admin rights, enterprise environment. I have tried the scoop built and your precompiled built. When I fire up broot without flags in powershell, the root path/top bar is not showing up. When I move around the file list, the window blinks sometimes and it shows the root path. When I toggle_trim_root it doesnt show it either/no reaction. If I start broot with -T, same behaviour. Have I missed something? On wezterm I have the same results. I'm vividly using broot on unix at home. 

Best regards,
flxn7

![2024-02-18 11_56_11-](https://github.com/Canop/broot/assets/160394919/3d13e427-c7c0-4c53-b98f-32dfb8113fc3)

![2024-02-18 12_01_48-](https://github.com/Canop/broot/assets/160394919/8139934c-c9c3-43e8-8a33-23502c32d1d8)

**Comment by tangent360** [comment]
For now you can roll back to 1.32.0 from Jan 2nd which is the latest release that does not have the issue.

**Comment by Canop** [comment]
I'll work on that as soon as possible. It's just not easy for me because I don't usually have a Windows computer available.

**Comment by chtenb** [comment]
In case it helps, I sometimes notice that broot starts flickering when e.g. resize, which is when the top line is sometimes visible. However, it always stabilizes on a state where the top is line not visible.

**Comment by Canop** [comment]
Some hints for courageous people willing to recompile broot:

broot 1.33 came with a new version of crossterm.
It's possible removing this part would help: https://github.com/Canop/broot/blob/main/src/app/app.rs#L861-L867
It's also possible it wouldn't be enough.

**Comment by Daverd-GM** [comment]
oh this is the bug I found when testing the NerdFontsIcons Pull request
this is what I found

Good night, I was trying to compile the Pull-Request for the [Nerd Fonts Icons](https://github.com/Canop/broot/pull/833) and I found a bug on the 1.33 and 1.33.1 tags in my machine which is:
|Operative System | Infromation|
|-|-|
Edición |	Windows 10 Home
Versión	|22H2
Se instaló el	|‎13/‎11/‎2022
Compilación del SO|	19045.4046
Experiencia	|Windows Feature Experience Pack 1000.19053.1000.0

|||
|-|-|
Nombre del dispositivo	|Laptop-Daverd
Procesador	|Intel(R) Core (TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
RAM instalada	|12,0 GB (11,8 GB utilizable)
Modelo el sistema | Aspire A315-56
Tipo de sistema	|Sistema operativo de 64 bits, procesador x64

 The bug is that every line shows one line above of where they should be the screen was flickering while I was moving with the arrows and the title bar which has the current Directory didn't render.
 Here is an image of the difference
 
|1.32|1.33 onwards|
![Screenshot of the difference of the issue showing an image.](https://miaou.dystroy.org/file-host/705aa99c95489de1e30f3386.jpg)

the flickering appears to show the for an instance the lines in the correct position but they quickly move up one line, the mouse detects them in the correct position, if I click the '3D Objects' folder in the right the selection would be the working directory and if I click the 'AppData' then the select would be the '3D Objects' folder

**Comment by chtenb** [comment]
> Some hints for courageous people willing to recompile broot:
> 
> broot 1.33 came with a new version of crossterm. It's possible removing this part would help: [`main`/src/app/app.rs#L861-L867](https://github.com/Canop/broot/blob/main/src/app/app.rs?rgh-link-date=2024-02-19T17%3A42%3A03Z#L861-L867) It's also possible it wouldn't be enough.

@Canop I've tested this, and it seems to solve the issue for me, as well as making broot do much less flickering during resizing.

**Comment by Canop** [comment]
@chtenb I pushed this change, it's in main : https://github.com/Canop/broot/commit/8c2af6758070a26231d66b5485093df0c808cc13

**Comment by Daverd-GM** [comment]
I compiled the last commit it works wonderful in Windows Terminal with PowerShell

**Comment by Canop** [comment]
I think it's OK in broot 1.34. Reopen if I'm wrong.
