### ISSUE TITLE
feature request: word wrapping in text preview

### ISSUE THREAD

**Issue by eddiehazel** [Canop/broot#893]
i am experimenting with using broot to manage my notes. the ui is so buttery and configurable, i really want this to be the entrypoint to a filesystem of text files i can use to organise my thoughts! 🧈 

i am pretty much a rust n00b but i do love it. i have limited ability and time at the moment but with a few pointers i perhaps could contribute if it is in fact as easy to implement as i'd hope it would

ideally i would love a full editor in there but that seems like a much more significant project! 😂

**Comment by Canop** [comment]
> i am pretty much a rust n00b but i do love it. i have limited ability and time at the moment but with a few pointers i perhaps could contribute if it is in fact as easy to implement as i'd hope it would

Please don't even try your hands with word wrapping. Doing it efficiently is far from trivial. If I decide to add this feature, I'll do it myself, using the many utilities I already have for that (see bacon's word wrapping for example).

More generally, broot isn't the ideal codebase for a newbie, partially because I was myself a noob in Rust when starting this project and it's still a little too messy due to that :)

(discussions regarding projects or features in need of contributions according to taste and abilities are welcome on [my chat](https://miaou.dystroy.org/3768))

**Comment by eddiehazel** [comment]
> More generally, broot isn't the ideal codebase for a newbie, partially because I was myself a noob in Rust when starting this project and it's still a little too messy due to that :)

i've been there! 😁 

all good, looking forward to it if you do!
